@startuml
'https://plantuml.com/sequence-diagram

title Specify New Vaccine Type - System Sequence Diagram


autonumber

actor "System Administrator" as Administrator
participant ":System" as System

activate Administrator

Administrator -> System: asks to specify new vaccine type
System --> Administrator: requests data (disease, short_description)

Administrator -> System: types requested data
System --> Administrator: shows all the data and requests confirmation

Administrator -> System: confirms the data
System --> Administrator: informs operation success
@enduml
