@startuml

hide circle
skinparam classAttributeIconSize 0
hide methods

title Specify New Vaccine Type

class Admin {
      - name
      - email
      - phone_number
  }

  class VaccineType {
       - type_code
       - disease
       - short_description
  }

Admin --> VaccineType: registers

@enduml