@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0


' ===== Enums / DTOs =====
  class FacilityType {
  HEALTHCARE
  COMMUNITY
}

class VaccinationCenterDTO {
  -name : string
  -postal_address : string
  -phone_number : string
  -email : string
  -website_address : string
  -opening_hours : string
  -closing_hours : string
  -max_vaccines_per_hour : int
  -facilityType : FacilityType
  -vaccineTypeCode : string
}

' ===== UI Layer =====
class RegisterVaccinationCenterView {
}

class RegisterVaccinationCenterController {
  +registerVaccinationCenter(dto : VaccinationCenterDTO) : void
  +saveRegistedVaccinationCenter(): Result
  +listVaccineTypes() : vector<shared_ptr<VaccineType>>
}

class App {
  +getVaccinationCenterService(): VaccinationCenterService
 }

RegisterVaccinationCenterView ..> RegisterVaccinationCenterController
RegisterVaccinationCenterController ..> VaccinationCenterDTO

' ===== Service Layer =====
class VaccinationCenterService {
+ VaccinationCenterService(VaccineCenterRepository VCRepo, shared_ptr<VaccineTypeRepository>)
+ create((string name, string postal_adress, string phone_number, string email, string website_address, string opening_hours, string closing_hours, int max_vaccines_per_hour): VaccinationCenter
+addOrUpdate(VaccinationCenter obj): Result
}

RegisterVaccinationCenterController ..> VaccinationCenterService

' ===== Repository Interfaces =====
interface VaccinationCenterRepository <<interface>> {
  +save(VaccinationCenter obj) : Result
}

interface VaccineTypeRepository <<interface>> {
  +findAll() : vector<shared_ptr<VaccineType>>
  +findByCode(code : string) : shared_ptr<VaccineType>
  +exists(code : string) : bool
}

' ===== Concrete Repositories (Memory) =====
    class VaccinationCenterMemoryRepository{
+ getVaccinationCenterRepository(): VaccinationCenterRepository
}
VaccinationCenterMemoryRepository .up.|> VaccinationCenterRepository

class VaccineTypeMemoryRepository {
  +findAll() : vector<shared_ptr<VaccineType>>
  +findByCode(code : string) : shared_ptr<VaccineType>
  +exists(code : string) : bool
}
VaccineTypeMemoryRepository .up.|> VaccineTypeRepository

' ===== Repository Factory =====
interface RepositoryFactory <<interface>>  {
   + getVaccinationCenterRepository(): VaccineCenterRepository
   + getVaccinationTypeRepository(): VaccineTypeRepository
  }


class MemoryRepositoryFactory {
  + getVaccinationCenterRepository(): VaccineCenterRepository
  + getVaccinationTypeRepository(): VaccineTypeRepository
}

App "1" -down-> "1" RepositoryFactory:  uses
App --> VaccinationCenterService: adopts
RepositoryFactory ..> VaccinationCenterRepository
RepositoryFactory ..> VaccineTypeRepository
VaccinationCenterService ..> VaccinationCenterRepository
VaccinationCenterService ..> VaccineTypeRepository
MemoryRepositoryFactory .up.|> RepositoryFactory
MemoryRepositoryFactory .right.> VaccinationCenterMemoryRepository
MemoryRepositoryFactory .right.> VaccineTypeMemoryRepository

' ===== Domain Model =====
 abstract class Facility {
  -name : string
  -postal_address : string
  -phone_number : string
  -email : string
  -website_address : string
  -opening_hours : string
  -closing_hours : string
  -max_vaccines_per_hour : int
  Facility(string name, string postal_adress, string phone_number, string email, string website_address, string opening_hours, string closing_hours, int max_vaccines_per_hour)
}

class Healthcare_Center
class Community_Mass_Vaccination_Center {
  -vaccineType : shared_ptr<VaccineType>
}

Facility <|-- Healthcare_Center
Facility <|-- Community_Mass_Vaccination_Center

class VaccineType {
  -type_code : wstring
  -disease : wstring
  -short_description : wstring
}

VaccinationCenterRepository "1" --> "0..*" Facility : records >
VaccineTypeRepository "1" --> "0..*" VaccineType : records >

Community_Mass_Vaccination_Center "1" --> "1" VaccineType : administered >

@enduml
