@startuml
autonumber
autoactivate on

actor Admin as Admin
activate Admin

participant ":RegisterVaccinationCenterView" as View
participant ":RegisterVaccinationCenterController" as Controller
participant "App" as App
participant "service:VaccinationCenterService" as Service
participant "factory:RepositoryFactory" as RepoFactory
participant "dto:VaccinationCenterDTO" as CenterDto
participant "repoVT:VaccineTypeRepository" as VTRepo
participant "repoVC:VaccinationCenterRepository" as VCRepo


participant "vt:VaccineType" as VT
participant "hc:Healthcare_Center" as Healthcare
participant "cm:Community_Mass_Vaccination_Center" as Community

Admin -> View: requests to register a new vaccination center
View --> Admin: asks the facility type
Admin -> View: selects facilityType (HEALTHCARE/COMMUNITY)

alt facilityType = COMMUNITY

  View -> Controller: listVaccineTypes()
  Controller -> App: getVaccinationCenterService()
  App -> RepoFactory: getVaccineTypeRepository()
  RepoFactory --> App: VTRepo
  App --> Service**: create(VTRepo)
  App --> Controller: service
  Controller -> Service: listVaccineTypes()
  Service -> VTRepo: findAll()
  VTRepo --> Service: list<VaccineType>

  Service --> Service: map(list<VaccineType>) -> lstVTDto
  Service --> Controller: LstVTDto
  Controller --> View: LstVTDto

  View --> Admin: asks to select a vaccine type
  Admin -> View: selects vaccineTypeCode

  View --> Admin: requests facility data
  Admin -> View: types requested data

  View --> CenterDto**: create(facilityType, name, address, phone, email,\nwebsite, openingHours, closingHours,\nmaxVaccinesPerHour, vaccineTypeCode)

else facilityType = HEALTHCARE

  View --> Admin: requests facility data
  Admin -> View: types requested data

  View --> CenterDto**: create(facilityType, name, address, phone, email,\nwebsite, openingHours, closingHours,\nmaxVaccinesPerHour, null)

end

View --> Admin: shows all data and requests confirmation
Admin -> View: confirms the data

View -> Controller: registerVaccinationCenter(dto)
Controller -> Service: registerCenter(dto)

Service -> RepoFactory: getVaccinationCenterRepository()
RepoFactory --> Service: VCRepo

alt dto.facilityType == HEALTHCARE

  Service -> CenterDto: getName()
  CenterDto --> Service: name
  Service -> CenterDto: getOpeningHours()
  CenterDto --> Service: openingHours

  Service --> Healthcare**: create(from dto fields)
  Healthcare --> Service: Healthcare
  Service -> VCRepo: save(Healthcare)
  VCRepo --> Service: Result

else dto.facilityType == COMMUNITY

   Service -> CenterDto: getVaccineTypeCode()
  CenterDto --> Service: vaccineTypeCode

  Service -> RepoFactory: getVaccineTypeRepository()
  RepoFactory --> Service: VTRepo
  Service -> VTRepo: findByCode(vaccineTypeCode)
  VTRepo --> Service: VT

  Service --> Community**: create(from dto fields, VT)
  Community --> Service: Community
  Service -> VCRepo: save(Community)
  VCRepo --> Service: Result

end

Service --> Controller: Result
Controller --> View: Result
View --> Admin: informs operation success

@enduml
