project(Core)

add_library(Core
        headers/domain/shared/Result.h
        headers/domain/shared/StringUtils.h
        sources/domain/shared/Result.cpp
        sources/domain/shared/StringUtils.cpp
        headers/controllers/ui/CreateNewVaccineTypeController.h
        headers/domain/model/VaccineType.h
        sources/controllers/ui/App.cpp
        sources/controllers/ui/CreateNewVaccineTypeController.cpp
        sources/domain/model/VaccineType.cpp
        ../ConsoleApp/headers/views/CreateNewVaccineTypeView.h
        ../ConsoleApp/sources/views/CreateNewVaccineTypeView.cpp
        sources/domain/model/VaccineTypeContainer.cpp
        ../ConsoleApp/headers/views/MainView.h
        ../ConsoleApp/sources/views/MainView.cpp
        # US11 - Register Vaccine
        headers/domain/model/VaccineTechnology.h
        sources/domain/model/VaccineTechnology.cpp
        headers/domain/model/Vaccine.h
        sources/domain/model/Vaccine.cpp
        headers/domain/model/VaccineContainer.h
        sources/domain/model/VaccineContainer.cpp
        headers/controllers/ui/RegisterVaccineController.h
        sources/controllers/ui/RegisterVaccineController.cpp
        headers/controllers/ui/ListEmployeesByRoleController.h
        sources/controllers/ui/ListEmployeesByRoleController.cpp
        sources/domain/model/EmployeeContainer.cpp
        sources/domain/model/Employee.cpp
        sources/controllers/ui/RegisterEmployeeController.cpp
        ../ConsoleApp/sources/views/RegisterEmployeeView.cpp
        ../ConsoleApp/sources/views/ListEmployeesByRoleView.cpp
        # US20 - Register SNS user
        headers/domain/model/SNSUser.h
        sources/domain/model/SNSUser.cpp
        headers/domain/model/SNSUserContainer.h
        sources/domain/model/SNSUserContainer.cpp
        headers/controllers/ui/RegisterSNSUserController.h
        sources/controllers/ui/RegisterSNSUserController.cpp
        ../ConsoleApp/headers/views/RegisterSNSUserView.h
        ../ConsoleApp/sources/views/RegisterSNSUserView.cpp
        sources/domain/services/SNSUserService.cpp
        sources/infrastructure/memory/MemoryRepositoryFactory.cpp
        sources/domain/model/CommunityMassVaccinationCenter.cpp
        sources/controllers/ui/RegisterVaccinationCenterController.cpp
        headers/domain/model/VaccinationProcess.h
        sources/domain/model/VaccinationProcess.cpp
        headers/controllers/dto/VaccinationProcessDTO.h
        headers/domain/repositories/VaccinationProcessRepository.h
        sources/infrastructure/memory/SNSUserMemoryRepository.cpp
        headers/domain/repositories/WaitingRoomRepository.h
        headers/domain/repositories/RecoveryRoomRepository.h
        headers/domain/services/VaccinationProcessService.h
        sources/domain/services/VaccinationProcessService.cpp
        headers/infrastructure/memory/VaccinationProcessMemoryRepository.h
        sources/infrastructure/memory/VaccinationProcessMemoryRepository.cpp
        headers/infrastructure/memory/WaitingRoomMemoryRepository.h
        sources/infrastructure/memory/WaitingRoomMemoryRepository.cpp
        headers/infrastructure/memory/RecoveryRoomMemoryRepository.h
        sources/infrastructure/memory/RecoveryRoomMemoryRepository.cpp
        headers/controllers/ui/RecordVaccinationController.h
        sources/controllers/ui/RecordVaccinationController.cpp
        ../ConsoleApp/headers/views/RecordVaccinationView.h
        ../ConsoleApp/sources/views/RecordVaccinationView.cpp
        sources/domain/model/CommunityMassVaccinationCenter.cpp
)