@startuml

title US15 - Domain Model

hide circle
skinparam classAttributeIconSize 0
skinparam classAttributeIconSize 0
hide circle
hide methods

class Employee {
 -employee_id
     -name
     -postalAddress
     -phoneNumber
     -email
     -citizenCardNumber
     -role
}

class Nurse {

}

class Receptionist {

}

class Admin{
    - name
    - email
    - phoneNumber
}
Employee <|-- Nurse
Employee <|-- Receptionist
Admin "1" -right-- "1..*" Employee: register >

@enduml