@startuml
autoactivate on
autonumber

actor Receptionist as Receptionist
activate Receptionist


participant RegisterSNSUserView as View
participant RegisterSNSUserController as Controller
participant SNSUserService as Service
participant RepositoryFactory as Factory
participant SNSUserRepository as Repo
participant SNSUser as UserObj

Receptionist -> View: requests to register an SNS user
View --> Receptionist: asks for the user data
Receptionist -> View: provide name, date of birth, sex, postal address, phone number, email, citizen card number, sns user number

View -> Controller: registerUser(dto : SNSUserDTO)
Controller -> Service: register(dto)
Service -> Factory: getSNSUserRepository()
Factory --> Service: Repo

' Check uniqueness of data
Service -> Repo: existsByPhoneNumber(dto.phoneNumber)
Repo --> Service: bool
Service -> Repo: existsByEmail(dto.email)
Repo --> Service: bool
Service -> Repo: existsByCitizenCardNumber(dto.citizenCardNumber)
Repo --> Service: bool
Service -> Repo: existsBySNSUserNumber(dto.snsUserNumber)
Repo --> Service: bool

' Success path (all unique)
Service -> Service: createSNSUser(dto)
Service --> UserObj**: createSNSUser(dto)
UserObj --> Service: SNSUser
Service -> Repo: save(UserObj)
Repo --> Service: Result
Service --> Controller: Result(success)
Controller --> View: Result(success)
View --> Receptionist: informs registration success

alt [duplicate found]
    Service --> Controller: Result(failure)
    Controller --> View: Result(failure)
    View --> Receptionist: informs that phone/email/cc or sns user number already exists
end

@enduml
