@startuml
'https://plantuml.com/sequence-diagram

title Register SNS User – System Sequence Diagram

autonumber

actor "Receptionist" as Receptionist
participant ":System" as System

activate Receptionist

Receptionist -> System: selects register SNS user
System --> Receptionist: requests data (name, dateOfBirth, sex, postalAddress, phoneNumber, email, citizenCardNumber, snsUserNumber)
Receptionist -> System: types requested data
System --> Receptionist: shows all data and requests confirmation
Receptionist -> System: confirms registration
System --> Receptionist: informs operation success

@enduml
