@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

actor "Receptionist" as Receptionist
participant ":RegisterSNSUserView" as View
participant ":RegisterSNSUserController" as Ctrl
participant ":SNSUserService" as Service
participant "factory:RepositoryFactory" as Factory
participant "repo:SNSUserRepository" as Repo
participant "obj:SNSUser" as UserObj

activate Receptionist

Receptionist -> View: requests to register an SNS user
View --> Receptionist: asks for the user data
Receptionist -> View: provide name, date of birth, sex, postal address, phone number, email, citizen card number, sns user number

View -> Ctrl: registerUser(dto : SNSUserDTO)
Ctrl -> Service: register(dto)
Service -> Factory: getSNSUserRepository()
Factory --> Service: Repo

' Check uniqueness of data
Service -> Repo: existsByPhoneNumber(dto.phoneNumber)
Repo --> Service: bool
Service -> Repo: existsByEmail(dto.email)
Repo --> Service: bool
Service -> Repo: existsByCitizenCardNumber(dto.citizenCardNumber)
Repo --> Service: bool
Service -> Repo: existsBySNSUserNumber(dto.snsUserNumber)
Repo --> Service: bool
Service --> Ctrl: ok

' Show data to Receptionist for confirmation
Ctrl --> View: ok
View --> Receptionist: show all data for confirmation
Receptionist -> View: confirms data
activate View
View --> Ctrl: confirmed data
activate Ctrl
Ctrl -> Service: createSNSUser(dto)
Service -> Service: createSNSUser(dto)
Service --> UserObj: createSNSUser(dto)
activate UserObj
UserObj --> Service: SNSUser
Service -> Repo: save(UserObj)
Repo --> Service: Result
Service --> Ctrl: Result(success)
Ctrl --> View: Result(success)
View --> Receptionist: informs registration success


@enduml
