@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
    - name
    - email
    - phone_number
}

class Employee {
    - Employee_id
    - name
    - postal_address
    - phone_number
    - email
    - citizen_card_number
    - role
}

class Nurse {
}

class Receptionist {
}

Administrator "1" -right-- "0..*" Employee: registers >
Employee <|-- Nurse
Employee <|-- Receptionist

@enduml