@startuml
' System Sequence Diagram for US41 – Record vaccine administration
title Register vaccine administration – System Sequence Diagram

autoactivate on
autonumber

actor "Nurse" as Nurse
participant ":System" as System

activate Nurse

Nurse -> System: selects record vaccine administration
System --> Nurse: requests data (SNS user number, vaccine code, lot number)
Nurse -> System: types requested data
System --> Nurse: removes SNS user from waiting room and shows all data and requests confirmation
Nurse -> System: confirms registration
System --> Nurse: assigns SNS user to recovery room and informs operation success

@enduml
