@startuml

title US15 - Get List of Employees by Role - Sequence Diagram

autoactivate on
autonumber

actor "Admin" as Admin

activate Admin

participant ":ListEmployeesByRoleView" as view
participant ":ListEmployeesByRoleController" as ctrl
participant ":App" as app
participant "container:EmployeeContainer" as container

Admin -> view: request employee list by role
view --> Admin: show role selection options
Admin -> view: selects desired role
view -> ctrl: requestEmployeeList(role)
ctrl -> app: getEmployeeContainer()
app --> ctrl: container
ctrl -> container: getEmployeeListByRole(role)
container --> ctrl: list of employees
ctrl --> view: list of employees
view --> Admin: display list


@enduml