@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber


actor Receptionist as recep
participant RegisterUserArrivalView as View
participant RegisterUserArrivalController as controller
participant App as app

activate recep

participant "factory:RepositoryFactory" as repofact
participant "service:UserArrivalService" as service
participant "vcr:VaccinationCenterRepository" as vaccentrepo
participant "sr:SNSUserRepository" as userrepo
participant "uar:UserArrivalRepository" as arrvlrepo
participant "dtoList:List<FacilityDto>" as FacilityDtoList
participant "dto:<UserDto>" as userdto

participant "arrival:UserArrival" as arrival


recep -> View: requests to register a user arrival

View -> controller: listFacilities()
controller -> app: getRepositoryFactory()
app --> controller: repofact
app -> repofact: getVaccinationCenterRepository()
repofact --> app: vaccentrepo
app --> service**: create(vaccentrepo)
app --> controller: vaccentrepo
controller -> vaccentrepo: findAll()
vaccentrepo --> controller: facilities
controller -> FacilityDtoList**: create(facilities)
controller --> View: facilityDtoList

View --> recep: asks to select the facility
recep -> View: selects facility

View --> recep: asks to select a SNS_User_Number
recep -> View:  types a SNS_User_Numberr

View -> controller: getSNSUserSummary(sns_user_number)
controller -> app: getRepositoryFactory()
app --> controller: repofact
app -> repofact: getSNSUserRepository()
repofact --> app: userrepo
app --> service**: create(userrepo)
app --> controller: userrepo
controller -> userrepo: findBySNSUserNumber(sns_user_number)
userrepo --> controller: user
controller -> userdto**: create(user)
controller --> View: userdto

View -> View: prepares arrival data
View --> recep: asks for confirmation
recep -> View: confirms data

View -> controller: registerArrival(DTO)

controller -> app: getRepositoryFactory()
app --> controller: repofact
controller -> repofact: getUserArrivalRepository()
repofact --> controller: arrvlrepo
controller -> repofact: getSNSUserRepository()
repofact --> controller: userrepo
controller -> repofact: getVaccinationCenterRepository()
repofact --> controller: vaccentrepo

controller -> service: UserArrivalService(arrvlrepo, userrepo, vaccentrepo)

controller -> service: registerArrival(DTO)

service -> service: day = getCurrentDate()
service -> userrepo: findBySNSUserNumber(DTO.sns_user_number)
userrepo --> service: user
service -> vaccentrepo: findById(DTO.facilityId)
vaccentrepo --> service: facility

create arrival
service -> arrival: UserArrival(now, user, facility)

service -> arrvlrepo: save(arrival)
arrvlrepo --> service: Result OK

service -> service: assigns SNS_User to waiting_room (implicit)
service --> controller: Result OK
controller --> View: Result OK
View --> recep: informs success of the operation

@enduml
