@startuml

autonumber
actor Receptionist as R

participant RegisterUserArrivalView as V
participant RegisterUserArrivalController as C
participant App as A
participant UserArrivalService as S

participant "RepositoryFactory" as RF
participant "VaccinationCenterRepository" as VCR
participant "SNSUserRepository" as SR
participant "UserArrivalRepository" as UAR

participant "UserArrivalDTO" as DTO
participant "Facility" as F
participant "SNSUser" as U
participant "UserArrival" as UA


R -> V: requests to register a user arrival
V -> C: listFacilities()
C -> A: getRepositoryFactory()
A --> C: RF
C -> RF: getVaccinationCenterRepository()
RF --> C: VCR
C -> VCR: findAll()
VCR --> C: facilities
C --> V: facilities

V --> R: asks to select the facility
R -> V: selects facility


V --> R:  asks to select a SNS_User_Number
R -> V: types a SNS_User_Number

V -> C: getSNSUserSummary(sns_user_number)
C -> A: getRepositoryFactory()
A --> C: RF
C -> RF: getSNSUserRepository()
RF --> C: SR
C -> SR: findBySNSUserNumber(sns_user_number)
SR --> C: U
C --> V: U

V -> V: records arrival time (now)

V -> V: builds DTO(facilityId, sns_user_number)
V --> R: asks for confirmation (shows DTO data)
R -> V: confirms data


V -> C: registerArrival(DTO)
C -> A: getUserArrivalService()
A --> C: S
C -> S: registerArrival(DTO)

S -> S: day = getCurrentDate()
S -> S: arrival_time = now()

S -> RF: getVaccinationCenterRepository()
RF --> S: VCR
S -> VCR: findById(DTO.facilityId)
VCR --> S: F

S -> RF: getSNSUserRepository()
RF --> S: SR
S -> SR: findBySNSUserNumber(DTO.sns_user_number)
SR --> S: U

create UA
S -> UA: UserArrival(arrival_time, U, F)

S -> RF: getUserArrivalRepository()
RF --> S: UAR
S -> UAR: save(UA)
UAR --> S: Result OK

S -> S: assigns SNS_User to waiting_room (implicit)
S --> C: Result OK
C --> V: Result OK
V --> R: informs success of the operation

@enduml
