@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Receptionist" as user
participant ":System" as system

 user -> system:requests to register a user arrival

system --> user:asks to select the facility

user -> system: selects facility

system --> user: asks to select a SNS_User_Number

user -> system: types a SNS_User_Number

system --> system: records arrival time

system --> user: asks for confirmation

user -> system: confirms data

system --> system: assigns the SNS_User to a waiting_room

system --> user: informs the sucess of the operation

@enduml